# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: xeroz369.BKStudyDesk
PackageVersion: 1.2.4
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.17763.0
InstallerType: exe
Scope: user
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: --silent
  SilentWithProgress: --silent
  InstallLocation: --installto "<INSTALLPATH>"
UpgradeBehavior: install
ProductCode: BKStudyDesk
ReleaseDate: 2026-10-10
AppsAndFeaturesEntries:
- DisplayName: BK Study Desk
  Publisher: xeroz369
  ProductCode: BKStudyDesk
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/xeroz369/bk-study-desk/releases/download/v1.2.4/BKStudyDesk-1.2.4-Setup-x64.exe
  InstallerSha256: CA6BD45914CB52B30CF4E3F3E4DBA483205369E015765D5E5308E22510A0B39E
- Architecture: arm64
  InstallerUrl: https://github.com/xeroz369/bk-study-desk/releases/download/v1.2.4/BKStudyDesk-1.2.4-Setup-arm64.exe
  InstallerSha256: BE76A1F2ECB02BDBDDF02B66675DB514A590CF9A053291410AD043A13C1BDF83
ManifestType: installer
ManifestVersion: 1.12.0
