# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: xeroz369.BKStudyDesk
PackageVersion: 1.2.3
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.17763.0
InstallerType: exe
Scope: user
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: --silent
  SilentWithProgress: --silent
  InstallLocation: --installto "<INSTALLPATH>"
UpgradeBehavior: install
ProductCode: BKStudyDesk
ReleaseDate: 2026-10-09
AppsAndFeaturesEntries:
- DisplayName: BK Study Desk
  Publisher: xeroz369
  ProductCode: BKStudyDesk
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/xeroz369/bk-study-desk/releases/download/v1.2.3/BKStudyDesk-1.2.3-Setup-x64.exe
  InstallerSha256: 27E730F34292478A5521A8139EABD09765612C3ACB7AD1839287A5DE11D6FC0D
- Architecture: arm64
  InstallerUrl: https://github.com/xeroz369/bk-study-desk/releases/download/v1.2.3/BKStudyDesk-1.2.3-Setup-arm64.exe
  InstallerSha256: 8BF32F604BC8CADE695BF9F6CB863F9D4674A0EE53104BD1B4D3E6DE5E42DB50
ManifestType: installer
ManifestVersion: 1.12.0
